# Generated by Django 3.2.5 on 2021-07-27 11:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='gallery', verbose_name='Картинка'),
        ),
    ]
