# Generated by Django 3.2.5 on 2021-07-24 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.PositiveSmallIntegerField(verbose_name='Номер столика')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('start', models.TimeField(verbose_name='Начало брони')),
                ('end', models.TimeField(verbose_name='Конец брони')),
                ('date', models.DateField(verbose_name='Дата')),
                ('taste', models.CharField(max_length=4096, verbose_name='Вкус')),
                ('sturdiness', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Крепкость')),
                ('wishes', models.TextField(verbose_name='Пожелания')),
                ('before_arrival', models.BooleanField(default=False, verbose_name='Забить до прихода')),
            ],
        ),
    ]
