# Generated by Django 3.2.5 on 2021-08-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'бронь', 'verbose_name_plural': 'брони'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'стол', 'verbose_name_plural': 'столы'},
        ),
    ]
