# Generated by Django 3.2.5 on 2021-07-24 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='sturdiness',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Крепкость'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='taste',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Вкус'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='wishes',
            field=models.TextField(blank=True, null=True, verbose_name='Пожелания'),
        ),
    ]
